# SwiftLint configuration for OrbitCove

# Paths to ignore during linting
excluded:
  - .build
  - Packages
  - OrbitCoveApp.xcodeproj
  - OrbitCoveAppTests

# Rules that are enabled
opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rules to disable
disabled_rules:
  - trailing_whitespace

# Line length
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_interpolated_strings: true

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 1000

# Function body length
function_body_length:
  warning: 60
  error: 100

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Identifier name
identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 50
  excluded:
    - id
    - x
    - y
    - to
    - i
    - j
    - k
    - ok
    - or

# Type name
type_name:
  min_length:
    warning: 3
  max_length:
    warning: 50

# Nesting
nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

# Force casts
force_cast: warning

# Force try
force_try: warning

# Large tuple
large_tuple:
  warning: 4
  error: 5

# Custom rules
custom_rules:
  no_print:
    name: "No print statements"
    regex: "print\\s*\\("
    match_kinds:
      - identifier
    message: "Use os_log or Logger instead of print()"
    severity: warning
